### ISSUE TITLE
solc 0.4.17 compile errors for pure functions

### ISSUE THREAD

**Issue by elenadimitrova** [sc-forks/solidity-coverage#131]
With the `truffle` 4 beta 2 release which includes the `solc@0.4.17` upgrade instrumented contracts containing functions decorated with `view` will generate a Warning, while those marked as `pure` will Error with
```
TypeError: Function declared as pure, but this expression (potentially) reads from the environment or state and thus requires "view".
```
This is due to the SC instrumented function containing events (which modify state) being present in the `pure` function.

**Comment by area** [comment]
For now, I think the only way to solve this is to remove the `pure` and `view` decorators during instrumentation.

**Comment by cgewecke** [comment]
Published: `0.2.6`

@elenadimitrova Believe this is fixed but please re-open if you see weird visual alignment problems in the report, or crashing .... :)

**Comment by elenadimitrova** [comment]
Thanks @cgewecke 
Compilation failed for me in the following scenario:
Contract inhering from another which lives outside the `/contracts` folder, e.g. a git submodule library for me specifically it looks like this:
```
/contracts/Token.sol
/lib/dappsys/erc20.sol
```
This generates compile error:
```
/coverageEnv/contracts/Token.sol:25:5: TypeError: Overriding function changes state mutability from "view" to "nonpayable".
    function totalSupply() public returns (uint256) {__FunctionCoverageToken('/contracts/Token.sol',1);
    ^
Spanning multiple lines.
/coverageEnv/lib/dappsys/erc20.sol:23:5: Overriden function is here:
    function totalSupply() public view returns (uint supply);
    ^-------------------------------------------------------^
```

**Comment by cgewecke** [comment]
@elenadimitrova Thanks, yes that makes sense. Opening a separate issue for this.

**Comment by cgewecke** [comment]
@elenadimitrova  Hopefully fixed in `0.2.7`.  Try again?

**Comment by elenadimitrova** [comment]
Confirming as fixed and closing.
Thanks again @cgewecke !

**Comment by sweatyc** [comment]
I still have this issue on 0.5.7.

I have a `tokenURI()` function that override OpenZeppeline's ERC721Token.sol:
```
function tokenURI(uint256 _tokenId) public view returns (string) {
    require(exists(_tokenId), "Token ID not exists.");
   ...
}
```

Then I got this error:
```
,/Users/fur/Projects/Block42/landpot-dapp/coverageEnv/contracts/Land.sol:379:3: TypeError: Overriding function changes state mutability from "view" to "nonpayable".
  function tokenURI(uint256 _tokenId) public  returns (string) {emit __FunctionCoverageLand('/Users/fur/Projects/Block42/landpot-dapp/contracts/Land.sol',20);
  ^ (Relevant source part starts here and spans across multiple lines).
openzeppelin-solidity/contracts/token/ERC721/ERC721.sol:31:3: Overriden function is here:
  function tokenURI(uint256 _tokenId) public view returns (string);
  ^---------------------------------------------------------------^
Compilation failed. See above.
Cleaning up...
Shutting down testrpc-sc (pid 34087)
Event trace could not be read.
Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! block42-monopoly@1.0.0 coverage: `solidity-coverage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the block42-monopoly@1.0.0 coverage script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fur/.npm/_logs/2018-08-24T00_49_28_152Z-debug.log
```

**Comment by nithinkrishna** [comment]
I seem to be facing the same issue with `0.5.8`.

```
/project/coverageEnv/contracts/MyContract.sol:237:5: TypeError: Overriding function changes state mutability from "view" to "nonpayable".
    function allowance(address owner, address spender) public  returns (uint256) {emit __FunctionCoverageMyContract('/project/coverageEnv/contracts/MyContract.sol',12);
    ^ (Relevant source part starts here and spans across multiple lines).
openzeppelin-zos/contracts/token/ERC20/ERC20.sol:11:3: Overriden function is here:
  function allowance(address owner, address spender) public view returns (uint256);
  ^-------------------------------------------------------------------------------^
```
`MyContract.sol` inherits from `openzeppelin-zos/contracts/token/ERC20/ERC20.sol` and implments the allowance function with the same signature.
```
function allowance(address owner, address spender) public view returns (uint256) {
     // IMPL     
 }
```

**Comment by cgewecke** [comment]
@sweatyc @nithinkrishna Could either of you link to your projects? I will take a quick look.

**Comment by nithinkrishna** [comment]
@cgewecke I've setup a new project replicating the issue
https://github.com/nithinkrishna/solidity-coverage-issue-131

**Comment by cgewecke** [comment]
@nithinkrishna I was able to get the example to run without problems by removing everything from `.solcover.js` *except*:
```
module.exports = {
  copyPackages: ['openzeppelin-zos', 'openzeppelin-solidity'],
};
```
and just running `./node_modules/.bin/solidity-coverage`. 

The npm installed contract dependencies have to be explicitly copied into the `coverageEnv` folder to be instrumented correctly. Sorry about this - it's kind of inconvenient. 

Additionally, there's something very odd about the behavior of the two require statements you have at the top of that file. They interfere with the `copyPackages` option. I couldn't get it to work without commenting these out:
```javascript
const _require = require('app-root-path').require;
//const config = _require('/truffle.js').networks.testrpcCoverage;
```

**Comment by sweatyc** [comment]
Here's a isolated repository containing only solidity scripts and limited libraries:
https://github.com/Block42World/landpot-contracts

I updated to solidity-coverage 0.5.8 but nothing changed.
All scripts can be compile and passed tests, but failed on solidity-coverage...

This is the complete dpp project with frontend etc, in case you need it too:
https://github.com/Block42World/landpot-dapp

**Comment by cgewecke** [comment]
@sweatyc I got it to run by adding a `.solcover.js` with the following contents. Basically same as the previous comment:
```
module.exports = {
  copyPackages: ['openzeppelin-solidity']
}
```

There's an additional issue in the landpot-contracts where there is a migrations file that doesn't work (2) but just deleted it and everything was fine.

**Comment by nithinkrishna** [comment]
@cgewecke Thanks a ton! Works fine now. 
It's probably a good idea to maybe add this to the FAQ section.

**Comment by cgewecke** [comment]
@nithinkrishna Yes, completely agree - the README need a rewrite - it's bewildering and lots of information that should be foregrounded is buried deep in the options. When the tool was first written it was less common for people to install contracts with npm whereas now it's completely standard. Will do this week.

**Comment by bingen** [comment]
hey @cgewecke I'm having the same problem here:
https://github.com/aragon/aragon-apps/pull/425/commits/2da188ff9351779a7dc244232421881d1eb251a0
take `apps/vault`, which is kind of simple.
I tried your suggestion, so modified `.solcover.js` to:
```
module.exports = {
    copyPackages: ['@aragon/os']
}
`
And then I run `./node_modules/.bin/solidity-coverage .`, but I get the following error:
```
,/home/bingen/workspace/aragon-apps/apps/vault/coverageEnv/contracts/Vault.sol:175:5: TypeError: Overriding function changes state mutability from "view" to "nonpayable".
    function allowRecoverability(address) public  returns (bool) {emit __FunctionCoverageVault('/home/bingen/workspace/aragon-apps/apps/vault/contracts/Vault.sol',7);
    ^ (Relevant source part starts here and spans across multiple lines).
@aragon/os/contracts/common/VaultRecoverable.sol:37:5: Overriden function is here:
    function allowRecoverability(address token) public view returns (bool) {
    ^ (Relevant source part starts here and spans across multiple lines).
```
Could it be due to the folder structure of the package, with 2 subfolders? I'm seeing that under `coverageEnv` it appears as just `os` instead of `@aragon/os`.

**Comment by cgewecke** [comment]
@bingen If you just use `@aragon` does that work? It looks like we're not handling org name-spacing correctly and this needs it's own issue.

**Comment by bingen** [comment]
@cgewecke Yes, it works. I'm going to submit a PR with a workaround that worked for me too.

**Comment by PaulRBerg** [comment]
Sorry to notify y'all, but this still doesn't work in `0.5.11`. Here's my project [repo](https://github.com/ChronosProtocol/poc/tree/erc).

My `.solcover.js` file:

```node
module.exports = {
	port: 8555,
	skipFiles: ["base"],
	testrpcOptions: "--port 8555"
};
```

I get:

```
Compilation warnings encountered:

/Users/paulrberg/Documents/Projects/Chronos/PoC/coverageEnv/contracts/base/Ownable.sol:28:3: Warning: Function state mutability can be restricted to view
  function owner() public  returns(address) {
  ^ (Relevant source part starts here and spans across multiple lines).
,/Users/paulrberg/Documents/Projects/Chronos/PoC/coverageEnv/contracts/base/Ownable.sol:43:3: Warning: Function state mutability can be restricted to view
  function isOwner() public  returns(bool) {
  ^ (Relevant source part starts here and spans across multiple lines).
,/Users/paulrberg/Documents/Projects/Chronos/PoC/coverageEnv/contracts/base/SafeMath.sol:12:3: Warning: Function state mutability can be restricted to pure
  function mul(uint256 a, uint256 b) internal  returns (uint256) {
  ^ (Relevant source part starts here and spans across multiple lines).
,/Users/paulrberg/Documents/Projects/Chronos/PoC/coverageEnv/contracts/base/SafeMath.sol:29:3: Warning: Function state mutability can be restricted to pure
  function div(uint256 a, uint256 b) internal  returns (uint256) {
  ^ (Relevant source part starts here and spans across multiple lines).
,/Users/paulrberg/Documents/Projects/Chronos/PoC/coverageEnv/contracts/base/SafeMath.sol:40:3: Warning: Function state mutability can be restricted to pure
  function sub(uint256 a, uint256 b) internal  returns (uint256) {
  ^ (Relevant source part starts here and spans across multiple lines).
,/Users/paulrberg/Documents/Projects/Chronos/PoC/coverageEnv/contracts/base/SafeMath.sol:50:3: Warning: Function state mutability can be restricted to pure
  function add(uint256 a, uint256 b) internal  returns (uint256) {
  ^ (Relevant source part starts here and spans across multiple lines).
,/Users/paulrberg/Documents/Projects/Chronos/PoC/coverageEnv/contracts/base/SafeMath.sol:61:3: Warning: Function state mutability can be restricted to pure
  function mod(uint256 a, uint256 b) internal  returns (uint256) {
  ^ (Relevant source part starts here and spans across multiple lines).

Writing artifacts to ./build/contracts
```

I also tried:

```node
module.exports = {
	copyPackages: ["openzeppelin-solidity"],
};
```

And import openzeppelin in my project instead of the `base` folder. Any suggestions?

**Comment by PaulRBerg** [comment]
Nevermind the comment above, those were warnings not errors. I saw https://github.com/sc-forks/solidity-coverage/issues/365 and I understand that it's a corollary of using solidity-coverage.

But I don't think #822 solved the issue with the org name imports. I still have to type `@openzeppelin` rather than `@openzeppelin/contracts-ethereum-package`.

@cgewecke is that so?

**Comment by cgewecke** [comment]
@PaulRBerg [aragon-apps](https://github.com/aragon/aragon-apps/blob/master/apps/agent/.solcover.js) is the project that most resembles your use case and AFAIK it's resolving stuff correctly there. 

Do you see differences between their setup and yours that might resolve this question?

**Comment by PaulRBerg** [comment]
@cgewecke sorry, I conflated the error I found in #264 with the one here. I confirm that I can use `@openzeppelin/contracts-ethereum-package` in the [protocol package](https://github.com/sablierhq/sablier/tree/develop/packages/protocol), where I import external contracts only from @openzeppelin.
